### ISSUE TITLE
Implement the initial theme customizations

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse-theme-biofabforum#1]
The following list contains the customizations to be done to this theme, based on the internal default Discourse theme (with "Light" color scheme) as a starting point. In order of importance:

1. Change the theme's color scheme to "Biofabforum" again. (It was "Dark Simple" so far, but no need for the dark one as proof-of-theme-change anymore.)
2. Exchange the logo. The logo should be an asset in the "Biofabforum" remote theme. The b&w logo to use for now (with a transparent background please) has been supplied by e-mail.
3. Exchange the favicon. For that (for now) use the b&w microscope graphic (scaled and with white background), which which has been supplied by e-mail.
4. Don't add any main menu for now to the theme.
5. Add a footer section instead. It should allow to include several links in several columns, as plain HTML. No need for sub-menus as in the edgeryders.eu header now.
6. Add a link to [their Facebook group](https://www.facebook.com/groups/fungalmaterials/) as one of these footer links. Maybe with a Facebook icon and the Facebook group name "Fungal Materials & Biofabrication".
7. Add the "Powered by" as last line in the footer, in a different formatting than the footer links, and with width "left to right" (with reasonable margins, sure). The line content should be (with links):
    > Powered by: [Edgeryders](https://edgeryders.eu/); [Magma Nova](http://magmanova.com/); whatever other partner will join
8. Hide all top-level categories except category "Biofabrication" from the `/categories` page and the hamburger menu category navigation, using CSS.
9. Style the sub-categories of category "Biofabrication" so that they appear like main categories on the `/categories` page and in the hamburger menu category navigation. (This also implies that the "one and only" real main category "Biofabrication" should not be shown at all anymore, only its sub-categories.)
10. Hide all tags from topics, both in lists and on topic pages. Ideally keep them visible for admins and moderators, but that is optional (as admins and moderators can always work from the edgeryders.eu interface as well).

Helpful documentation about Discourse themes:

* [How to develop custom [remote] themes](https://meta.discourse.org/t/60848) (by Discourse)
* [Create and share a font [or other asset] theme component [in a remote theme]](https://meta.discourse.org/t/62462) (by Discourse)
* [Creating a custom Discourse theme](https://edgeryders.eu/t//7) (by Edgeryders)

**Edit 2018-01-29:** Updates integrated [from the ongoing discussion on edgeryders.eu](https://edgeryders.eu/t/8019/9).

**Comment by tanius** [comment]
This issue seems almost done already :slightly_smiling_face: Here's one additional requirement for point number 9 ("style the sub-categories in the list") though:

If the subcategory has a category image set in its configuration, it should be displayed in the category overview list. Its size and formatting can / should be done as for the main category images in the [category list on edgeryders.eu](https://edgeryders.eu/categories).

Since the logo of sub-categories may not be available on the `/categories` page, you may have to modify the handlebars template. That is possible within Discourse themes ([example](https://github.com/SamSaffron/discourse-simple-theme/blob/master/desktop/header.html), [instructions](https://meta.discourse.org/t/41281)).

I have now set the "[Biofabrication](https://edgeryders.eu/c/biofab)" category on Edgeryders to be publicly accessible, and added five sub-categories to it. I have also hidden it in the edgeryders.eu Default theme, so you can now use that category on biofabrication.org to try out things (incl. adding logos to its sub-categories). You'll not create a mess on edgeryders.eu, as these categories are only shown on biofabrication.org until you finished developing them. Good luck :slightly_smiling_face:

**Comment by damingo** [comment]
Done.
