### ISSUE TITLE
Render description_excerpt on the main category list

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse-theme-biofabforum#2]
On the `/categories` overview page, this theme renders sub-categories as if they were top-level categories, as it is meant to do.

So far there is a small hack involved: subcategory templates are not provided with the `description_excerpt` value as top-level categories are, so it is not possible to render the shortened category description by rendering this value. However, the entire description is available, so this is rendered instead and then abridged using the `text-overlow: ellipsis` attribute in CSS.

In the long term, it would be a cleaner solution to provide `description_excerpt` to subcategory templates. Could even just be reported to Discourse upstream, and waiting for them to fix it.

**Comment by damingo** [comment]
No longer needed as a different solution avoided this problem.
