### ISSUE TITLE
Hide the main category dropdown on sub-category pages

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse-theme-biofabforum#3]
Currently,  the sub-category topic lists are not yet customized, such as this one for the "[Biofabrication → Social](https://biofabforum.org/c/biofab/social)" sub-category. On these pages, the top-left dropdown to select the main category should be completely hidden away. This way, people will not be confused about the navigation of the site.

**Comment by damingo** [comment]
Done, but I can't close this issue as I do not have sufficient rights.
