### ISSUE TITLE
Hide unrelated categories when a new topic is created

### ISSUE THREAD

**Issue by damingo** [edgeryders/discourse-theme-biofabforum#5]
When a new topic is created on biofabforum.org any category can be selected in the dropdown. This must be limited to biofabforum subcategories.

**Comment by tanius** [comment]
When doing this in a sub-category page (as the Biofabforum page will be in a bit …), only subcategories and "Uncategorized" are visible in the dropdown. So in this case, hide "Uncategorized" with CSS, and it's solved for us.
