### ISSUE TITLE
Remove the global "Latest / New / Unread / Top" links from within Discourse

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse-theme-biofabforum#6]
Visiting these links by clicking on them on a Discourse page will bring the user to the global "Latest", "New" and ""Top" pages, which exposes the user to edgeryders.eu content ("and that's bad"). Similarly, the user can visit the global "Unread" page, but that would not be an issue as it will only contain biofabforum.org content for Biofabforum users. Still, it's redundant to the [Unread page in the Biofabforum category](https://biofabforum.org/c/biofab/l/unread), so better we remove the global "Unread" link as well.

These links are already redirected to their counterparts within the Biofabforum category using Apache `mod_rewrite`, but that does not help with Discourse as it intercepts these links on-click and does not send a standard HTTP request for them afterwards.

So instead, we have to hide them (with CSS and / or Handlebars templates) wherever they are visible in Discourse:

* "Latest", "New", "Unread" and "Top" in the hamburger menu
* Discourse main top navigation bar (there should be no links to that, but just in case users find a way there …)

**Comment by damingo** [comment]
Done.
